---

- 
  hosts : all

  tasks : 
    - name : Create new Users
      user :
        name : "{{ item }}"
        state : present
      with_items :
        - user1
        - user2
        - user3

...

