---

-
  hosts : all

  tasks :
    - name : When Example task1 
      command : hostname -s
      when : ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

    - name : When Example task2
      command : hostname -s
      when : ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

...
