---

-
  hosts : Centos1

  tasks :
    - name : When Example task1 
      command : hostname -s
      when : 
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version >= "5"
      register : command_register

    - name : Show Register
      debug : 
        var : command_register

    - name : Show Command is changed
      debug :
        var : command_register.changed

    - name : Install patch when changed
      yum :
        name : patch
        state : present
      when : command_register is changed

    - name : Install patch when skipped
      yum :
        name : patch 
        state : present 
      when : command_register is skipped
        
...
